apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: dougtidwell/nexus-jetty:0.2
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
            - containerPort: 5000
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector:
    app: nexus
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8081
  - name: docker
    port: 5000
    targetPort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/ssl-redirect: true
spec:
  rules:
  - host: nexus.REPLACE_DOMAIN_NAME
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus
          servicePort: 80
  - host: docker.REPLACE_DOMAIN_NAME
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus
          servicePort: 5000
  tls:
  - hosts:
    - nexus.REPLACE_DOMAIN_NAME
    - docker.REPLACE_DOMAIN_NAME
    secretName: nexus-tls

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi